---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-git
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: mytest3
        image: gaya3sudhi/python-git
        ports:
        - containerPort: 80
